name: clavisafe
services:
  backend:
    build:
      context: ../backend
      dockerfile: docker/backend.Dockerfile
    container_name: clavisafe-backend
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ../backend:/var/www/html
    user: "${UID}:${GID}"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=${COMPOSER_ALLOW_SUPERUSER}
      - HOME=/tmp
    depends_on:
      - db
    networks:
      - clavisafe_net

  frontend:
    build: 
      context: ../frontend
      dockerfile: docker/frontend.Dockerfile
    container_name: clavisafe-frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ../frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - clavisafe_net
        
  db:
    image: mysql:8.0
    container_name: clavisafe-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_databasetfg:/var/lib/mysql
    networks:
      - clavisafe_net
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: clavisafe-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db
    networks:
      - clavisafe_net

volumes:
  db_databasetfg:

networks:
  clavisafe_net: